application: the-record-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /api/.*
  script: api.app

- url: /jobs/.*
  script: jobs.app

- url: /tasks/.*
  script: tasks.app

- url: /.*
  script: app.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
